#!/usr/bin/env bash
# =============================================================================
# generate-file-summaries.sh — Generate per-file analysis prompts for AI
#
# Usage: ./generate-file-summaries.sh /path/to/project [extensions]
#
# Arguments:
#   project_path    Path to the project directory
#   extensions      Comma-separated list of extensions (default: ts,tsx,js,jsx,py,rs,go,rb,java,kt,vue,svelte)
#
# This script does NOT call an AI API. It generates markdown files containing
# source code wrapped in an analysis prompt template. You then feed these to
# your AI tool of choice.
#
# Output: Creates refactor-notes/file-analysis/ with one .md file per source file.
# =============================================================================

set -euo pipefail

PROJECT_PATH="${1:-}"
EXTENSIONS="${2:-ts,tsx,js,jsx,mjs,cjs,py,rs,go,rb,java,kt,vue,svelte}"

if [[ -z "$PROJECT_PATH" ]]; then
  echo "Usage: ./generate-file-summaries.sh /path/to/project [extensions]" >&2
  echo "" >&2
  echo "Examples:" >&2
  echo "  ./generate-file-summaries.sh ./my-project" >&2
  echo "  ./generate-file-summaries.sh ./my-project ts,tsx,js,jsx" >&2
  echo "  ./generate-file-summaries.sh ./my-project py" >&2
  exit 1
fi

if [[ ! -d "$PROJECT_PATH" ]]; then
  echo "Error: Directory not found: $PROJECT_PATH" >&2
  exit 1
fi

PROJECT_PATH="$(cd "$PROJECT_PATH" && pwd)"

MAX_FILE_SIZE=50000  # Skip files larger than 50KB

# Build find pattern from extensions
IGNORE_PATTERN='node_modules|\.git/|dist/|build/|coverage/|\.next/|\.nuxt/|__pycache__|\.venv|venv/|\.tox|\.mypy_cache|\.pytest_cache|target/|vendor/|\.cache/'

# Build extension regex
ext_regex=""
IFS=',' read -ra EXT_ARRAY <<< "$EXTENSIONS"
for ext in "${EXT_ARRAY[@]}"; do
  ext=$(echo "$ext" | tr -d ' ')
  if [[ -n "$ext_regex" ]]; then
    ext_regex="$ext_regex|"
  fi
  ext_regex="$ext_regex\.$ext$"
done

# Create output directory
OUTPUT_DIR="$PROJECT_PATH/refactor-notes/file-analysis"
mkdir -p "$OUTPUT_DIR"

# Find source files (exclude test files)
source_files=$(find "$PROJECT_PATH" -type f 2>/dev/null \
  | grep -vE "$IGNORE_PATTERN" 2>/dev/null \
  | grep -E "$ext_regex" 2>/dev/null \
  | grep -vE '\.test\.|\.spec\.|__tests__/' 2>/dev/null \
  | sort) || true

if [[ -z "$source_files" ]]; then
  total=0
else
  total=$(echo "$source_files" | wc -l | tr -d ' ')
fi
echo "Found $total source files to analyze."
echo ""

generated=0
skipped=0

while IFS= read -r file; do
  [[ -z "$file" ]] && continue

  relative_path="${file#$PROJECT_PATH/}"
  file_size=$(wc -c < "$file" | tr -d ' ')

  # Skip large files
  if [[ "$file_size" -gt "$MAX_FILE_SIZE" ]]; then
    echo "⏭  Skipping (too large): $relative_path ($((file_size / 1024))KB)"
    skipped=$((skipped + 1))
    continue
  fi

  line_count=$(wc -l < "$file" | tr -d ' ')

  # Generate safe output filename
  safe_name=$(echo "$relative_path" | sed 's|[/\\]|__|g' | sed 's|\.|-|g')
  output_file="$OUTPUT_DIR/${safe_name}.md"

  # Write analysis prompt
  cat > "$output_file" << PROMPT_EOF
# File Analysis: $relative_path

**Lines:** $line_count
**Generated by:** Refactor Pilot — generate-file-summaries.sh

---

Analyze this source file and produce a structured summary:

1. **Purpose** (one sentence)
   What does this file do? What is its primary responsibility?

2. **Exports**
   List everything this file exports (functions, classes, components, constants, types).
   For each export, describe what it does in one line.

3. **Imports & Dependencies**
   - Internal imports (other project files)
   - External imports (npm packages, pip packages, etc.)
   - Note any circular dependency risks

4. **Complexity Indicators**
   - Line count: $line_count
   - Number of functions/methods
   - Nesting depth (deepest level)
   - Any functions over 50 lines

5. **Code Smells**
   Identify if present: duplicated logic, god functions, long parameter lists,
   magic numbers, mixed responsibilities, global mutation, commented-out code,
   TODO/FIXME notes, excessive \`any\` types, \`!important\` in CSS.

6. **Data Flow**
   - Where does this file get its data?
   - Where does it send data?
   - Any side effects?

7. **Refactoring Opportunities**
   Suggest 1-3 specific refactoring actions.

---

## Source Code

\`\`\`
$(cat "$file")
\`\`\`
PROMPT_EOF

  echo "✅ Generated: $relative_path"
  generated=$((generated + 1))

done <<< "$source_files"

echo ""
echo "Done. Generated $generated analysis prompts, skipped $skipped."
echo "Output directory: $OUTPUT_DIR"
echo ""
echo "Next step: Feed these files to your AI tool for analysis."
echo "You can process them individually or concatenate them for batch analysis:"
echo "  cat $OUTPUT_DIR/*.md > combined-analysis.md"
